# webhook info
webhookUrl: https://hooks.slack.com/services/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
                                                                 
webhookChannel: 99_listener_check

# server info
serverInfos:
- name: DEV
  isNotiWhenTrue: false
  serverUrl: http://1.255.144.21:8080
- name: BMT
  isNotiWhenTrue: false
  serverUrl: http://1.255.98.178:8080
- name: PROD
  isNotiWhenTrue: false
  serverUrl: http://1.255.112.155:8080

# url path & parameter
listenerPath: /idxr/set/kafkaListener?
propertiesPath: /property?
checkParam: status=Y
solveParam: use_yn=Y
propertiesParam: m=getPropertyList


spring:
  data:
    elasticsearch:
      devCluster-name: els-cluster
      bmtCluster-name: els-cluster
  elasticsearch:
    jest:
      proxy:
        devHost: 1.255.144.24
        devPort: 9300 
        bmtHost: 1.255.98.109 
        bmtPort: 9300
        
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp